### PR TITLE
V2

### PR DESCRIPTION
**Pull request by jasonmcintosh**
Here's initial pull request with fixes.  Can work from this :)

### CODE REVIEW

**Comment by ventz** [comment]
@jasonmcintosh For the waflambdafiles - let's do a mix of both the customer name and the random string:
${var.customer}-waflambdafiles-${random_string.lambda_bucket.result}

If you are changing things, mind doing a pull on your copy to remove the zip from the PR so that I can merge it through the web page? (I can do it manually, but it's really convenient through the web)

**Comment by ventz** [comment]
@jasonmcintosh Great - Thanks. I can see you are pushing literally right now, so let me know when you are done, and I'll merge the PR.

**Comment by jasonmcintosh** [comment]
Note still got more testing to do - didn't get a chance tonight to run that, will do so tomorrow ;)  Thanks for the merge!!

**Comment by ventz** [comment]
@jasonmcintosh Great - thanks. PR Merged.

**Pull request merged**
