### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by mikerj1**
random string sometimes contains uppercase characters, which are not valid for S3 bucket names

### CODE REVIEW

**Comment by mikerj1** [comment]
Changed pull request to v2 branch

**Comment by ventz** [comment]
@mikerj1 Incredible PR! Great job on the changes and fixes.

Let me go through it, but so far it looks good!

**Comment by ventz** [comment]
@mikerj1 Could you break this up into "upgrades" vs "improvements".

That is, "upgrades" being the new node_modules and 3rd-party functions that are replacing/upgrading Amazon's provided code

vs

"Improvements" -- all of the new improvements you are introducing.

Just so that it's easier/a bit more sane to go through.

There are 322 changes files currently...

**Comment by mikerj1** [comment]
I think the fact that I initially chose the wrong branch is making this look far more impressive than it is.  It is a one line change. May be better to reject and I can submit properly again.

**Comment by ventz** [comment]
@mikerj1 Ok, closing it so you can resubmit.

**Pull request closed without merging**
